window.speciesData = {
  species_metasequoia_glyptostroboides_data: {
    genus: "Metasequoia",
    species: "glyptostroboides",
    commonName: "Dawn Redwood",
    abbreviation: "M. glyptostroboides",
    ploidy: "Diploid",
    chromosomeNumber: "2n=2x=22",
    genomeSize: "11.6 Gb",
    genomeAssemblies: "1",
    grinTaxonomy: "40144",
  },

  species_sequoiadendron_giganteum_data: {
    genus: "Sequoiadendron",
    species: "giganteum",
    commonName: "Giant Sequoia",
    abbreviation: "S. giganteum",
    ploidy: "Diploid",
    chromosomeNumber: "2n=2x=22",
    genomeSize: "11.6 Gb",
    genomeAssemblies: "1",
    grinTaxonomy: "40144",
  },

  species_taxus_chinensis_data: {
    genus: "Taxus",
    species: "chinensis",
    commonName: "Chinese Yew",
    abbreviation: "T. chinensis",
    ploidy: "Diploid",
    chromosomeNumber: "2n=2x=22",
    genomeSize: "11.6 Gb",
    genomeAssemblies: "1",
    grinTaxonomy: "40144",
  },

  species_torreya_grandis_data: {
    genus: "Torreya",
    species: "grandis",
    commonName: "Chinese Nutmeg Tree",
    abbreviation: "T. grandis",
    ploidy: "Diploid",
    chromosomeNumber: "2n=2x=22",
    genomeSize: "11.6 Gb",
    genomeAssemblies: "1",
    grinTaxonomy: "40144",
  },

  species_larix_kaempferi_data: {
    genus: "Larix",
    species: "kaempferi",
    commonName: "Japanese Larch",
    abbreviation: "L. kaempferi",
    ploidy: "Diploid",
    chromosomeNumber: "2n=2x=22",
    genomeSize: "11.6 Gb",
    genomeAssemblies: "1",
    grinTaxonomy: "40144",
  },

  species_pinus_tabuliformis_data: {
    genus: "Pinus",
    species: "tabuliformis",
    commonName: "Chinese Red Pine",
    abbreviation: "P. tabuliformis",
    ploidy: "Diploid",
    chromosomeNumber: "2n=2x=22",
    genomeSize: "11.6 Gb",
    genomeAssemblies: "1",
    grinTaxonomy: "40144",
  },

  species_ginkgo_biloba_data: {
    genus: "Ginkgo",
    species: "biloba",
    commonName: "Ginkgo",
    abbreviation: "G. biloba",
    ploidy: "Diploid",
    chromosomeNumber: "2n=2x=22",
    genomeSize: "11.6 Gb",
    genomeAssemblies: "1",
    grinTaxonomy: "40144",
  },
};
